### ISSUE TITLE
Inaccurate prediction

### ISSUE THREAD

**Issue by AmethystZeroAtwell** [pavitrakumar78/Street-View-House-Numbers-SVHN-Detection-and-Classification-using-CNN#6]
Hi, I have a clear house number image,however I can't get the correct predict.
What kind of pretreatment should I do?
Thank you for your time.
![1](https://user-images.githubusercontent.com/44636205/54171357-00850e00-44b5-11e9-9fbb-0ab7d8d83886.png)
![2](https://user-images.githubusercontent.com/44636205/54171372-0da1fd00-44b5-11e9-81bb-1c66f336c039.png)

**Comment by pavitrakumar78** [comment]
I'm not quite sure of this. Have you tried to replicate the results mentioned in the readme of the project? you can find the test IDs [here](https://github.com/pavitrakumar78/Street-View-House-Numbers-SVHN-Detection-and-Classification-using-CNN/tree/master/correctly%20classified%20examples).

If you are able to reproduce those results, then I guess the network just needs more tuning and/or more pre-processing of images.

**Comment by AmethystZeroAtwell** [comment]
Thanks for your response!
I replicate your test data successfully,however I can't recognize the picture above. Could you tell me how can I pre-process the image or other methods.

**Comment by pavitrakumar78** [comment]
There are a few points mentioned in the [improvements](https://github.com/pavitrakumar78/Street-View-House-Numbers-SVHN-Detection-and-Classification-using-CNN#improvements-that-can-be-made) section of the readme. Try those methods. Other than that, I'd say the biggest improvement can only come from advanced CNN architectures. Since this is a task where the input to the 2nd (recognition) CNN is actually the output of the 1st (detection) CNN, I would say making improvements to the detection would result in better digits recognition.  
Try this: take the image in your post, crop it so that only the digits are visible and then send it to the recognition CNN - see whether it recognizes the digits correctly. If it does, then the work is to be done on the CNN that does the detection part (i.e, getting the cropped digits section from input image)

**Comment by AmethystZeroAtwell** [comment]
Thank you for your advice. I will try to improve it. :-)
